name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint with ruff
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          ruff check .
      - name: Run tests and collect coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest --cov=./ --cov-report=xml:coverage.xml -q
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      # Optional: upload to Codecov (requires CODECOV_TOKEN secret for private repos)
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: coverage.xml
